services:
  # Microservicio service-usuarios
  service-usuarios:
    build: ./service-usuarios
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_HOST=usuarios-db
      - DB_USER=adminserviceusuarios
      - DB_PASS=admin123
      - DB_NAME=usuarios_db
    depends_on:
      - usuarios-db
  # base de datos mysql para service-usuarios
  usuarios-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: usuarios_db
      MYSQL_USER: adminserviceusuarios
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  # Microservicio service-tareas
  service-tareas:
    build: ./service-tareas
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - DB_HOST=tareas-db
      - DB_PORT=27017
      - DB_NAME=tareas_db
    depends_on:
      - tareas-db
  # base de datos para service-tareas
  tareas-db:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mysql-data:
  mongo-data: